### ISSUE TITLE
How to count LOC in whole project

### ISSUE THREAD

**Issue by janisz** [warmans/golocc#5]
I'd like to count LOC in my whole project. Ideally if golocc supports `./...` expansion`and ignore`vendor` directory.

**Comment by warmans** [comment]
I don't really remember at all how this project works but I guess it would be easy to at least add excluded directories to prevent vendor from being parsed e.g. an `--no-vendor` flag. For the `./...` thing  it seems this library provides helpers: https://godoc.org/github.com/kisielk/gotool but I'll have to see exactly how it would be implemented.

**Comment by warmans** [comment]
Now works more more like it should. From within a package golocc ./... will process all files/subpackages. Including --no-vendor will ignore anything with "/vendor/" in the path. 

Referencing a package outside the working dir is still weird because it requires the absolute path. I will fix this at some point. I guess it should look in the gopath.
